Repository AY2324S1-CS2103T-T11-1/tp, pull requests merged in 2023-11, with the labels that each got.

#124 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/MarkPresentSequenceDiagram.puml
Labels: type.Task, Priority.Medium

#135 Fix selected student not resetting on Clear command
  src/main/java/seedu/classmanager/MainApp.java
  src/main/java/seedu/classmanager/logic/commands/ClearCommand.java
  src/main/java/seedu/classmanager/model/Model.java
  src/main/java/seedu/classmanager/model/ModelManager.java
  src/test/java/seedu/classmanager/commons/core/VersionTest.java
  src/test/java/seedu/classmanager/logic/commands/AddCommandTest.java
Labels: type.Bug

#145 Add feature absent all
  docs/UserGuide.md
  src/main/java/seedu/classmanager/logic/commands/MarkAbsentAllCommand.java
  src/main/java/seedu/classmanager/logic/parser/ClassManagerParser.java
  src/main/java/seedu/classmanager/logic/parser/MarkAbsentAllCommandParser.java
  src/main/java/seedu/classmanager/ui/HelpWindow.java
  src/test/java/seedu/classmanager/logic/commands/MarkAbsentAllCommandTest.java
  src/test/java/seedu/classmanager/logic/parser/ClassManagerParserTest.java
  src/test/java/seedu/classmanager/logic/parser/MarkAbsentAllCommandParserTest.java
Labels: Priority.Medium

#148 Fix exception handling in random
  docs/UserGuide.md
  src/main/java/seedu/classmanager/logic/commands/RandomCommand.java
  src/main/java/seedu/classmanager/logic/parser/RandomCommandParser.java
  src/test/java/seedu/classmanager/logic/commands/RandomCommandTest.java
  src/test/java/seedu/classmanager/logic/parser/RandomCommandParserTest.java
Labels: type.Bug, Priority.Medium

#150 Fix prefix error
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/Logo.png
  docs/images/SeEduLogo.png
  docs/images/sample-contents.png
  src/main/java/seedu/classmanager/logic/parser/AddCommandParser.java
  src/main/java/seedu/classmanager/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/classmanager/logic/parser/CliSyntax.java
  src/main/java/seedu/classmanager/logic/parser/CommentCommandParser.java
  src/main/java/seedu/classmanager/logic/parser/ConfigCommandParser.java
  src/main/java/seedu/classmanager/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/classmanager/logic/parser/EditCommandParser.java
  src/main/java/seedu/classmanager/logic/parser/LoadCommandParser.java
  src/main/java/seedu/classmanager/logic/parser/LookupCommandParser.java
  src/main/java/seedu/classmanager/logic/parser/MarkAbsentAllCommandParser.java
  src/main/java/seedu/classmanager/logic/parser/MarkAbsentCommandParser.java
  src/main/java/seedu/classmanager/logic/parser/MarkPresentAllCommandParser.java
  src/main/java/seedu/classmanager/logic/parser/MarkPresentCommandParser.java
  src/main/java/seedu/classmanager/logic/parser/RecordClassParticipationCommandParser.java
  src/main/java/seedu/classmanager/logic/parser/SetGradeCommandParser.java
  src/main/java/seedu/classmanager/logic/parser/TagCommandParser.java
  src/main/java/seedu/classmanager/logic/parser/ViewCommandParser.java
  src/main/resources/images/address_book_32.png
  src/main/resources/view/StudentListCard.fxml
  src/test/java/seedu/classmanager/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/CommentCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/ConfigCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/LoadCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/LookupCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/MarkAbsentAllCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/MarkAbsentCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/MarkPresentAllCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/MarkPresentCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/RandomCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/RecordClassParticipationCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/SetGradeCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/ViewCommandParserTest.java
Labels: type.Bug, severity.Medium

#149 Modify Load and Config commands
  data/logicmanagertest.json
  docs/UserGuide.md
  src/main/java/seedu/classmanager/logic/LogicManager.java
  src/main/java/seedu/classmanager/logic/Messages.java
  src/main/java/seedu/classmanager/logic/commands/ConfigCommand.java
  src/main/java/seedu/classmanager/logic/commands/MarkAbsentAllCommand.java
  src/main/java/seedu/classmanager/logic/commands/MarkAbsentCommand.java
  src/main/java/seedu/classmanager/logic/commands/MarkPresentAllCommand.java
  src/main/java/seedu/classmanager/logic/commands/MarkPresentCommand.java
  src/main/java/seedu/classmanager/logic/parser/ClassManagerParser.java
  src/main/java/seedu/classmanager/logic/parser/ConfigCommandParser.java
  src/main/java/seedu/classmanager/model/Model.java
  src/main/java/seedu/classmanager/model/ModelManager.java
  src/main/java/seedu/classmanager/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/classmanager/model/UserPrefs.java
  src/main/java/seedu/classmanager/model/student/ClassDetails.java
  src/main/java/seedu/classmanager/model/student/Student.java
  src/main/java/seedu/classmanager/storage/JsonAdaptedClassDetails.java
  src/main/java/seedu/classmanager/storage/JsonAdaptedStudent.java
  src/main/java/seedu/classmanager/ui/HelpWindow.java
  src/test/data/JsonClassManagerStorageTest/invalidAndValidStudentClassManager.json
  src/test/data/JsonLoadCommandTest/validClassManager.json
  src/test/data/JsonSerializableClassManagerTest/duplicateStudentClassManager.json
  src/test/data/JsonSerializableClassManagerTest/typicalStudentsClassManager.json
  src/test/data/JsonUserPrefsStorageTest/AfterConfiguredUserPref.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/classmanager/logic/LogicManagerTest.java
  src/test/java/seedu/classmanager/logic/commands/AddCommandTest.java
  src/test/java/seedu/classmanager/logic/commands/CommandTestUtil.java
  src/test/java/seedu/classmanager/logic/commands/ConfigCommandTest.java
  src/test/java/seedu/classmanager/logic/commands/MarkAbsentAllCommandTest.java
  src/test/java/seedu/classmanager/logic/commands/MarkAbsentCommandTest.java
  src/test/java/seedu/classmanager/logic/commands/MarkPresentAllCommandTest.java
  src/test/java/seedu/classmanager/logic/commands/MarkPresentCommandTest.java
  src/test/java/seedu/classmanager/logic/parser/ClassManagerParserTest.java
  src/test/java/seedu/classmanager/logic/parser/ConfigCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/MarkAbsentAllCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/MarkAbsentCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/MarkPresentAllCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/MarkPresentCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/RecordClassParticipationCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/SetGradeCommandParserTest.java
  src/test/java/seedu/classmanager/model/UserPrefsTest.java
  src/test/java/seedu/classmanager/model/student/ClassDetailsTest.java
  src/test/java/seedu/classmanager/storage/JsonAdaptedClassDetailsTest.java
  src/test/java/seedu/classmanager/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/classmanager/storage/JsonClassManagerStorageTest.java
  src/test/java/seedu/classmanager/storage/JsonUserPrefsStorageTest.java
Labels: type.Bug, priority.High

#151 Fix class manager not reading file bug
  src/main/java/seedu/classmanager/MainApp.java
  src/main/java/seedu/classmanager/model/ModelManager.java
Labels: type.Bug, priority.High, severity.High

#152 Fix minor bugs
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/classmanager/logic/commands/ConfigCommand.java
  src/main/java/seedu/classmanager/model/student/ClassDetails.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
Labels: type.Bug, severity.Low

#155 Standardised command parameters shown to user
  docs/UserGuide.md
  src/main/java/seedu/classmanager/commons/util/InvalidationListenerManager.java
  src/main/java/seedu/classmanager/logic/CommandHistory.java
  src/main/java/seedu/classmanager/logic/commands/AddCommand.java
  src/main/java/seedu/classmanager/logic/commands/CommentCommand.java
  src/main/java/seedu/classmanager/logic/commands/DeleteCommand.java
  src/main/java/seedu/classmanager/logic/commands/HistoryCommand.java
  src/main/java/seedu/classmanager/logic/commands/MarkAbsentAllCommand.java
  src/main/java/seedu/classmanager/logic/commands/MarkAbsentCommand.java
  src/main/java/seedu/classmanager/logic/commands/MarkPresentAllCommand.java
  src/main/java/seedu/classmanager/logic/commands/MarkPresentCommand.java
  src/main/java/seedu/classmanager/logic/commands/RandomCommand.java
  src/main/java/seedu/classmanager/logic/commands/RedoCommand.java
  src/main/java/seedu/classmanager/logic/commands/UndoCommand.java
  src/main/java/seedu/classmanager/model/Model.java
  src/main/java/seedu/classmanager/model/ModelManager.java
  src/main/java/seedu/classmanager/model/VersionedClassManager.java
  src/main/java/seedu/classmanager/model/student/StudentNumber.java
  src/main/java/seedu/classmanager/ui/CommandBox.java
  src/main/java/seedu/classmanager/ui/ListElementPointer.java
  src/test/java/seedu/classmanager/logic/CommandHistoryTest.java
  src/test/java/seedu/classmanager/logic/commands/AddCommandTest.java
  src/test/java/seedu/classmanager/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/classmanager/logic/commands/HistoryCommandTest.java
  src/test/java/seedu/classmanager/logic/commands/RedoCommandTest.java
  src/test/java/seedu/classmanager/logic/commands/UndoCommandTest.java
  src/test/java/seedu/classmanager/model/VersionedClassManagerTest.java
  src/test/java/seedu/classmanager/ui/ListElementPointerTest.java
Labels: type.Documentation

#191 Fix random
  docs/UserGuide.md
  src/main/java/seedu/classmanager/logic/commands/RandomCommand.java
  src/main/java/seedu/classmanager/logic/parser/RandomCommandParser.java
  src/main/java/seedu/classmanager/model/student/ClassDetails.java
  src/main/java/seedu/classmanager/ui/HelpWindow.java
  src/test/java/seedu/classmanager/logic/commands/RandomCommandTest.java
  src/test/java/seedu/classmanager/logic/parser/RandomCommandParserTest.java
Labels: priority.High, type.Documentation

#192 Fix PE-D bugs
  docs/UserGuide.md
  src/main/java/seedu/classmanager/MainApp.java
  src/main/java/seedu/classmanager/logic/commands/EditCommand.java
  src/main/java/seedu/classmanager/logic/commands/MarkAbsentAllCommand.java
  src/main/java/seedu/classmanager/logic/commands/MarkAbsentCommand.java
  src/main/java/seedu/classmanager/logic/commands/MarkPresentAllCommand.java
  src/main/java/seedu/classmanager/logic/commands/MarkPresentCommand.java
  src/main/java/seedu/classmanager/logic/commands/RecordClassParticipationCommand.java
  src/main/java/seedu/classmanager/logic/commands/RedoCommand.java
  src/main/java/seedu/classmanager/logic/commands/SetGradeCommand.java
  src/main/java/seedu/classmanager/logic/commands/UndoCommand.java
  src/main/java/seedu/classmanager/logic/parser/RecordClassParticipationCommandParser.java
  src/main/java/seedu/classmanager/logic/parser/SetGradeCommandParser.java
  src/main/java/seedu/classmanager/model/student/ClassDetails.java
  src/main/java/seedu/classmanager/model/student/StudentNumber.java
  src/test/java/seedu/classmanager/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/classmanager/logic/commands/RecordClassParticipationCommandTest.java
  src/test/java/seedu/classmanager/logic/commands/SetGradeCommandTest.java
  src/test/java/seedu/classmanager/logic/parser/RecordClassParticipationCommandParserTest.java
  src/test/java/seedu/classmanager/logic/parser/SetGradeCommandParserTest.java
  src/test/java/seedu/classmanager/model/student/StudentNumberTest.java
Labels: type.Bug

#198 Bug fixes
  docs/UserGuide.md
  docs/team/cikguseven.md
  issues.xls
  src/main/java/seedu/classmanager/logic/commands/ConfigCommand.java
  src/main/java/seedu/classmanager/model/student/ClassDetails.java
  src/main/java/seedu/classmanager/model/student/StudentNumber.java
Labels: type.Bug

#200 Update developer guide
  docs/DeveloperGuide.md
Labels: type.Documentation

#203 Update PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/helpMessage.png
  docs/team/cikguseven.md
  docs/team/lwz19.md
  src/main/java/seedu/classmanager/model/student/StudentNumber.java
  src/test/java/seedu/classmanager/model/student/StudentNumberTest.java
Labels: type.Documentation

#226 Fix edit message bug
  src/main/java/seedu/classmanager/logic/parser/EditCommandParser.java
  src/test/java/seedu/classmanager/logic/parser/EditCommandParserTest.java
Labels: type.Bug, severity.Low

#237 Improve code quality
  src/main/java/seedu/classmanager/logic/commands/RandomCommand.java
  src/test/java/seedu/classmanager/logic/commands/RandomCommandTest.java
Labels: type.Task

#234 Edit DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ClassInformation.puml
  docs/diagrams/LookupCommand.puml
  docs/diagrams/TagCommand.puml
  docs/diagrams/ThemeSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/ViewCommand.puml
  docs/images/ViewCommand.png
  docs/images/helpMessage.png
  docs/images/johndoe.png
  docs/images/load-before.png
  docs/images/load-outcome.png
  docs/images/lookupClassResult.png
  docs/images/lookupNameResult.png
  docs/images/tag-success.png
  docs/images/theme-dark.png
  docs/images/theme-light.png
  docs/team/johndoe.md
  src/main/java/seedu/classmanager/MainApp.java
  src/main/java/seedu/classmanager/logic/commands/LookupCommand.java
  src/main/java/seedu/classmanager/logic/parser/ConfigCommandParser.java
  src/main/java/seedu/classmanager/ui/HelpWindow.java
  src/test/java/seedu/classmanager/logic/parser/ConfigCommandParserTest.java
Labels: type.Documentation

#255 Update developer guide
  docs/DeveloperGuide.md
Labels: type.Documentation

#256 Fix random bug
  src/main/java/seedu/classmanager/logic/commands/RandomCommand.java
  src/test/java/seedu/classmanager/logic/commands/RandomCommandTest.java
Labels: type.Bug

#258 Modify UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/add-student-success.png
  docs/images/class-part-success.png
Labels: type.Documentation
