Repository AY2324S1-CS2103T-T11-1/tp, pull requests merged in 2023-10, with the labels that each got.

#33 Update user and developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#51 Add function
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/ClassNumber.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/StudentNumber.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/ClassNumberTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/StudentNumberTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#54 Add lookup command
  docs/UserGuide.md
  docs/images/lookupClassResult.png
  docs/images/lookupLastNameResult.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/LookupCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/LookupCommandParser.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/LookupCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/LookupCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/PersonContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/testutil/NameContainsKeywordsPredicateTest.java
Labels: priority.High

#56 Modify delete using student number
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/StudentNumber.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#71 Modify lookup command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/LookupCommand.java
  src/main/java/seedu/address/logic/parser/LookupCommandParser.java
  src/main/java/seedu/address/model/student/StudentContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/LookupCommandTest.java
  src/test/java/seedu/address/logic/parser/LookupCommandParserTest.java
  src/test/java/seedu/address/model/student/StudentContainsKeywordsPredicateTest.java
Labels: Priority.Medium

#73 Add class grades feature
  src/main/java/seedu/address/model/student/ClassDetails.java
  src/main/java/seedu/address/model/student/grades/Attendance.java
  src/main/java/seedu/address/model/student/grades/AttendanceTracker.java
  src/main/java/seedu/address/model/student/grades/ClassParticipation.java
  src/main/java/seedu/address/model/student/grades/ClassParticipationTracker.java
  src/test/java/seedu/address/model/student/grades/AttendanceTest.java
  src/test/java/seedu/address/model/student/grades/AttendanceTrackerTest.java
  src/test/java/seedu/address/model/student/grades/ClassParticipationTest.java
  src/test/java/seedu/address/model/student/grades/ClassParticipationTrackerTest.java
Labels: priority.High

#86 Add SetGrade and RecordClassPart command
  src/main/java/seedu/address/logic/commands/ConfigCommand.java
  src/main/java/seedu/address/logic/commands/RecordClassPartCommand.java
  src/main/java/seedu/address/logic/commands/SetGradeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/RecordClassPartCommandParser.java
  src/main/java/seedu/address/logic/parser/SetGradeCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/student/ClassDetails.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/grades/Assignment.java
  src/main/java/seedu/address/model/student/grades/AssignmentTracker.java
  src/main/java/seedu/address/model/student/grades/Attendance.java
  src/main/java/seedu/address/model/student/grades/AttendanceTracker.java
  src/main/java/seedu/address/model/student/grades/ClassParticipation.java
  src/main/java/seedu/address/model/student/grades/ClassParticipationTracker.java
  src/main/java/seedu/address/storage/JsonAdaptedClassDetails.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/test/data/JsonLoadCommandTest/validAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RecordClassPartCommandTest.java
  src/test/java/seedu/address/logic/commands/SetGradeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RecordClassPartCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SetGradeCommandParserTest.java
  src/test/java/seedu/address/model/student/ClassDetailsTest.java
  src/test/java/seedu/address/model/student/grades/AssignmentTrackerTest.java
  src/test/java/seedu/address/model/student/grades/AttendanceTrackerTest.java
  src/test/java/seedu/address/model/student/grades/ClassParticipationTrackerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClassDetailsTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
Labels: priority.High

#92 Add user guide and test cases for mark attendance
  docs/UserGuide.md
  src/main/java/seedu/address/model/student/grades/AttendanceTracker.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/model/student/grades/AttendanceTrackerTest.java
Labels: type.Task, priority.High

#93 Add visualisation for class grades
  src/main/java/seedu/address/model/student/ClassDetails.java
  src/main/java/seedu/address/model/student/grades/AssignmentTracker.java
  src/main/java/seedu/address/model/student/grades/AttendanceTracker.java
  src/main/java/seedu/address/model/student/grades/ClassParticipationTracker.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/java/seedu/address/model/student/ClassDetailsTest.java
  src/test/java/seedu/address/model/student/grades/AssignmentTrackerTest.java
  src/test/java/seedu/address/model/student/grades/AttendanceTrackerTest.java
  src/test/java/seedu/address/model/student/grades/ClassParticipationTrackerTest.java
Labels: type.Story, Priority.Medium

#103 Update Developer Guide
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/LoadSequenceDiagram.puml
  docs/images/load-outcome.png
  docs/images/t2-contents.png
  src/main/java/seedu/address/MainApp.java
Labels: priority.High

#98 Add-comment-feature
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/CommentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RecordClassPartCommand.java
  src/main/java/seedu/address/logic/commands/SetGradeCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CommentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/Comment.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonLoadCommandTest/validAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CommentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/model/student/grades/CommentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
Labels: type.Story, Priority.Medium

#102 Edit UG and DG
  build.gradle
  copyright.txt
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ClassGrades.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/Trackers.puml
  docs/diagrams/UiClassDiagram.puml
  docs/index.md
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/book.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: Priority.Medium

#108 Add defensive coding
  src/main/java/seedu/address/model/student/ClassDetails.java
  src/main/java/seedu/address/model/student/grades/AttendanceTracker.java
Labels: type.Task, Priority.Medium, severity.Low

#109 Add feature mark all attendance
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/MarkAllCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MarkAllCommandParser.java
  src/test/java/seedu/address/logic/commands/MarkAllCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/MarkAllCommandParserTest.java
Labels: type.Story, Priority.Medium

#110 Modify edit using student number
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/ClassDetails.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/StudentContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/ClassDetailCard.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
Labels: type.Story, priority.High

#113 Fix fxml and UG issues
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/resources/view/ClassDetailBox.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StudentListCard.fxml
Labels: type.Bug, severity.Medium

#118 Add feature random
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/RandomCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RandomCommandParser.java
  src/test/java/seedu/address/logic/commands/RandomCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RandomCommandParserTest.java
Labels: type.Story, Priority.Medium
